### ISSUE TITLE
EPIC: Comments

### ISSUE THREAD

**Issue by KitLavis** [KitLavis/insight-sardinia#10]
Create an app to allow users to comment on blog posts: 

- [x] Create the database model, template and form for blog comments
- [x] Allow both users and the admin to write comments
- [x] Allow user to CRUD their own comments

From user story https://github.com/KitLavis/insight-sardinia/issues/14
