### ISSUE TITLE
EPIC: User Registration

### ISSUE THREAD

**Issue by KitLavis** [KitLavis/insight-sardinia#11]
Allow users to create and manage user profiles:

- [x] Install django allauth
- [x] Allow user to register/create a profile
- [ ] Allow user to update/delete their profile
- [x] Add login/logout functionality

From user story https://github.com/KitLavis/insight-sardinia/issues/15
