### ISSUE TITLE
EPIC: Front-end design

### ISSUE THREAD

**Issue by KitLavis** [KitLavis/insight-sardinia#12]
- [x] Create base.html template to apply to all pages/views with custom CSS
- [x] Create home page (using the base template) with custom CSS
- [x] Create login/register page (using the base template) with custom CSS
- [x] All pages should be responsive across all device sizes

From user story https://github.com/KitLavis/insight-sardinia/issues/16
