### ISSUE TITLE
EPIC: About Information

### ISSUE THREAD

**Issue by KitLavis** [KitLavis/insight-sardinia#18]
- [x] Start about app
- [x] Create meet the authors page
- [x] Create and migrate database model for contributors
- [x] Write relevant views and urls
