### ISSUE TITLE
EPIC: Initial Setup

### ISSUE THREAD

**Issue by KitLavis** [KitLavis/insight-sardinia#5]
Prepare the IDE, database and create the blog app

- [x] Install libraries and frameworks
- [x] Hide sensitive information
- [x] Create blog app
- [x] Connect to Cloudinary
