### ISSUE TITLE
EPIC: Admin Panel

### ISSUE THREAD

**Issue by KitLavis** [KitLavis/insight-sardinia#9]
Allow the admin to CRUD blog posts and to approve comments left by users:

- [x] Create article model
- [x] Create super user
- [x] Install summernote
- [x] Allow the editing (adding, updating and deleting) of blog posts
- [x] Allow an inappropriate comment to be deleted

From user story https://github.com/KitLavis/insight-sardinia/issues/13
